en:
  languageCode: en
  languageName: english
  menu:
    main:
      - name: About
        url: '/#about'
        weight: 1
      - name: Certifications
        url: '/#certifications'
        weight: 2
      - name: Experiences
        url: '/#experiences'
        weight: 3
      - name: Technologies
        url: '/#technologies'
        weight: 4
      - name: Projects
        url: '/#projects'
        weight: 5
      - name: Testimonials
        url: '/#testimonials'
        weight: 6
      - name: Blog
        url: '/blog'
        weight: 9

hu:
  languageCode: hu
  languageName: magyar
  contentDir: content/hu
  title: Mikó János
  menu:
    main:
      - name: Rólam
        url: '/hu/#about'
        weight: 1
#      - name: Tanúsítványok
#        url: '/hu/#certifications'
#        parent: Rólam
#        weight: 1
#      - name: Tapasztalat
#        url: '/#experiences'
#        parent: Rólam
#        weight: 2
#      - name: Vélemények
#        url: '/#testimonials'
#        parent: Rólam
#        weight: 3
#      - name: Projektek
#        url: '/#projects'
#        parent: Rólam
#        weight: 4
      - name: Blog
        url: '/hu/blog'
        weight: 9
