en:
  languageCode: en
  languageName: english
  menu:
    main:
      - name: About
        url: '/#about'
        weight: 1
      - name: Certifications
        url: '/#certifications'
        weight: 2
      - name: Experiences
        url: '/#experiences'
        weight: 3
      - name: Technologies
        url: '/#technologies'
        weight: 4
      - name: Projects
        url: '/#projects'
        weight: 5
      - name: Testimonials
        url: '/#testimonials'
        weight: 6
      - name: Blog
        url: '/blog'
        weight: 9
      - name: ✂︎ Snippets
        url: '/snippets'
        weight: 11

hu:
  languageCode: hu
  languageName: magyar
  contentDir: content/hu
  title: Mikó János
  menu:
    main:
      - name: Rólam
        url: '/hu/#about'
        weight: 1
      - name: Tanúsítványok
        url: '/hu/#certifications'
        weight: 2
      - name: Tapasztalat
        url: '/hu/#experiences'
        weight: 3
      - name: Technológiák
        url: '/hu/#technologies'
        weight: 4
      - name: Projektek
        url: '/hu/#projects'
        weight: 5
      - name: Vélemények
        url: '/hu/#testimonials'
        weight: 6
