en:
  languageCode: en
  languageName: english
  menu:
    main:
      - name: About
        url: '/#self-introduction'
        weight: 1
      - name: Blog
        url: '/blog'
        weight: 2

hu:
  languageCode: hu
  languageName: magyar
  contentDir: content/hu
  title: Mik칩 J치nos
  menu:
    main:
      - name: R칩lam
        url: '/hu/#bemutatkoz치s'
        weight: 1
      - name: Blog
        url: '/hu/blog'
        weight: 2
