en:
  languageCode: en
  languageName: english

hu:
  languageCode: hu
  languageName: magyar
  contentDir: content/hu
  title: Mikó János
  menu:
    main:
      - name: Rólam
        url: '/hu/#rolam'
        weight: 1
      - name: Blog
        url: '/hu/blog'
        weight: 2
