main:
  - name: about
    url: '#about'
    weight: 1
  - name: blog
    url: /blog/
    weight: 2
#   - name: Docs
#     url: /docs/
#     weight: 3

language:
  - name: en
    url: '/'
  - name: hu
    url: '/hu/'