main:
  - name: About
    weight: 1
  - name: Certifications
    parent: About
    weight: 2
  - name: Technologies
    url: /tech/
    weight: 3
  - name: Blog
    url: /blog/
    weight: 9

language:
  - name: en
    url: '/'
  - name: hu
    url: '/hu/'